AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
    - 'test-jules-ruby.rb'
    - 'lib/jules-ruby/cli/banner.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'lib/jules-ruby/cli/sessions.rb'
    - 'lib/jules-ruby/cli/interactive/session_manager.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Exclude:
    - 'lib/jules-ruby.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/jules-ruby/cli.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/jules-ruby/cli/prompts.rb'
